wandb_version: 1

_current_progress_remaining:
  desc: null
  value: 1.0
_custom_logger:
  desc: null
  value: 'False'
_episode_num:
  desc: null
  value: 0
_episode_storage:
  desc: null
  value: None
_last_episode_starts:
  desc: null
  value: '[ True]'
_last_obs:
  desc: null
  value: "[[[[0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n\
    \   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]\n\n  [[0 0\
    \ 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n   [0 0 0\
    \ ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]\n\n  [[0 0 0 ... 0 0\
    \ 0]\n   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]\n   ...\n   [0 0 0 ... 0 0 0]\n\
    \   [0 0 0 ... 0 0 0]\n   [0 0 0 ... 0 0 0]]]]"
_last_original_obs:
  desc: null
  value: None
_logger:
  desc: null
  value: <stable_baselines3.common.logger.Logger object at 0x17cb9bb20>
_n_calls:
  desc: null
  value: 0
_n_updates:
  desc: null
  value: 0
_num_timesteps_at_start:
  desc: null
  value: 0
_stats_window_size:
  desc: null
  value: 100
_total_timesteps:
  desc: null
  value: 10000
_vec_normalize_env:
  desc: null
  value: None
_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.13
    start_time: 1715837802.246788
    t:
      1:
      - 1
      - 2
      - 3
      - 12
      - 55
      2:
      - 1
      - 2
      - 3
      - 12
      - 55
      3:
      - 1
      - 3
      - 22
      - 23
      - 35
      4: 3.10.13
      5: 0.13.11
      8:
      - 4
      - 5
action_noise:
  desc: null
  value: None
action_space:
  desc: null
  value: Discrete(18)
algo:
  desc: null
  value: DQN
batch_norm_stats:
  desc: null
  value: '[]'
batch_norm_stats_target:
  desc: null
  value: '[]'
batch_size:
  desc: null
  value: 32
buffer_size:
  desc: null
  value: 50000
device:
  desc: null
  value: cpu
env:
  desc: null
  value: <stable_baselines3.common.vec_env.vec_transpose.VecTransposeImage object
    at 0x1526fe590>
ep_info_buffer:
  desc: null
  value: deque([], maxlen=100)
ep_success_buffer:
  desc: null
  value: deque([], maxlen=100)
exploration_final_eps:
  desc: null
  value: 0.05
exploration_fraction:
  desc: null
  value: 0.1
exploration_initial_eps:
  desc: null
  value: 1.0
exploration_rate:
  desc: null
  value: 0.0
exploration_schedule:
  desc: null
  value: <function get_linear_fn.<locals>.func at 0x17cb9f400>
gamma:
  desc: null
  value: 0.99
gradient_steps:
  desc: null
  value: 1
learning_rate:
  desc: null
  value: 0.0001
learning_starts:
  desc: null
  value: 50000
lr_schedule:
  desc: null
  value: <function constant_fn.<locals>.func at 0x17cb6bbe0>
max_grad_norm:
  desc: null
  value: 10
n_envs:
  desc: null
  value: 1
num_timesteps:
  desc: null
  value: 0
observation_space:
  desc: null
  value: Box(0, 255, (3, 210, 160), uint8)
optimize_memory_usage:
  desc: null
  value: 'False'
policy:
  desc: null
  value: "CnnPolicy(\n  (q_net): QNetwork(\n    (features_extractor): NatureCNN(\n\
    \      (cnn): Sequential(\n        (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4,\
    \ 4))\n        (1): ReLU()\n        (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2,\
    \ 2))\n        (3): ReLU()\n        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1))\n        (5): ReLU()\n        (6): Flatten(start_dim=1, end_dim=-1)\n  \
    \    )\n      (linear): Sequential(\n        (0): Linear(in_features=22528, out_features=512,\
    \ bias=True)\n        (1): ReLU()\n      )\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=512, out_features=18, bias=True)\n    )\n  )\n\
    \  (q_net_target): QNetwork(\n    (features_extractor): NatureCNN(\n      (cnn):\
    \ Sequential(\n        (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n\
    \        (1): ReLU()\n        (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2,\
    \ 2))\n        (3): ReLU()\n        (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1,\
    \ 1))\n        (5): ReLU()\n        (6): Flatten(start_dim=1, end_dim=-1)\n  \
    \    )\n      (linear): Sequential(\n        (0): Linear(in_features=22528, out_features=512,\
    \ bias=True)\n        (1): ReLU()\n      )\n    )\n    (q_net): Sequential(\n\
    \      (0): Linear(in_features=512, out_features=18, bias=True)\n    )\n  )\n)"
policy_class:
  desc: null
  value: <class 'stable_baselines3.dqn.policies.CnnPolicy'>
policy_kwargs:
  desc: null
  value: '{}'
q_net:
  desc: null
  value: "QNetwork(\n  (features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=22528, out_features=512, bias=True)\n      (1):\
    \ ReLU()\n    )\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=512,\
    \ out_features=18, bias=True)\n  )\n)"
q_net_target:
  desc: null
  value: "QNetwork(\n  (features_extractor): NatureCNN(\n    (cnn): Sequential(\n\
    \      (0): Conv2d(3, 32, kernel_size=(8, 8), stride=(4, 4))\n      (1): ReLU()\n\
    \      (2): Conv2d(32, 64, kernel_size=(4, 4), stride=(2, 2))\n      (3): ReLU()\n\
    \      (4): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1))\n      (5): ReLU()\n\
    \      (6): Flatten(start_dim=1, end_dim=-1)\n    )\n    (linear): Sequential(\n\
    \      (0): Linear(in_features=22528, out_features=512, bias=True)\n      (1):\
    \ ReLU()\n    )\n  )\n  (q_net): Sequential(\n    (0): Linear(in_features=512,\
    \ out_features=18, bias=True)\n  )\n)"
replay_buffer:
  desc: null
  value: <stable_baselines3.common.buffers.ReplayBuffer object at 0x1540ac4c0>
replay_buffer_class:
  desc: null
  value: <class 'stable_baselines3.common.buffers.ReplayBuffer'>
replay_buffer_kwargs:
  desc: null
  value: '{}'
sde_sample_freq:
  desc: null
  value: -1
seed:
  desc: null
  value: None
start_time:
  desc: null
  value: 1715837810125998000
target_update_interval:
  desc: null
  value: 10000
tau:
  desc: null
  value: 1.0
tensorboard_log:
  desc: null
  value: ./dqn_tensorboard/
train_freq:
  desc: null
  value: 'TrainFreq(frequency=4, unit=<TrainFrequencyUnit.STEP: ''step''>)'
use_sde:
  desc: null
  value: 'False'
use_sde_at_warmup:
  desc: null
  value: 'False'
verbose:
  desc: null
  value: 1
