wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.11
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.13
    start_time: 1715795635.163529
    t:
      1:
      - 1
      - 55
      3:
      - 16
      - 23
      4: 3.10.13
      5: 0.13.11
      8:
      - 5
eval_episodes:
  desc: null
  value: 10
gamma:
  desc: null
  value: 0.999
learning_rate:
  desc: null
  value: 0.0001
num_parallel_envs:
  desc: null
  value: 1
random_seed:
  desc: null
  value: 4157
total_timesteps:
  desc: null
  value: 10000
